[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"

[deploy]
startCommand = "gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 300 --preload app:app"
healthcheckPath = "/health"
healthcheckTimeout = 300
startupTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.env]
PYTHONUNBUFFERED = "1"
FLASK_ENV = "production"
FLASK_APP = "app.py"
PORT = "8000" 