[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"

[deploy]
startCommand = "python app.py"
healthcheckPath = "/"
healthcheckTimeout = 60
startupTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.env]
PYTHONUNBUFFERED = "1"
FLASK_ENV = "production"
FLASK_APP = "app.py"
PORT = "8000" 