[build]
builder = "docker"

[deploy]
startCommand = "gunicorn --bind 0.0.0.0:$PORT app:app"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.env]
PYTHONUNBUFFERED = "1"
FLASK_ENV = "production"
FLASK_APP = "app.py" 